pg_ctrl/controller/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^checklist/$', views.ChecklistView.as_view(), name='checklist'),
    url(r'^inventory/$', views.InventoryView.as_view(), name='inventory'),
    url(r'^playbook/install/$', views.PlaybookInstallView.as_view(), name='playbook_install'),
    url(r'^playbook/failover/$', views.PlaybookFailoverView.as_view(), name='playbook_failover'),
    url(r'^playbook/add_standby/$', views.PlaybookAddStandbyView.as_view(), name='playbook_add_standby'),

    url(r'^hosts/create/$', views.CreateHostView.as_view(), name='create_host'),
]

pg_ctrl/monitor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^check_connection/$', views.CheckConnectionView.as_view(), name='check_connection'),
]

pg_ctrl/pg_ctrl/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^controller/', include("controller.urls", namespace="controller")),
    url(r'^monitor/', include("monitor.urls", namespace="monitor")),
]

pg_ctrl/controller/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
import shortuuid


def generate_uuid():
    return shortuuid.ShortUUID().random(length=22)

class BaseUUID(models.Model):
    uuid = models.CharField(max_length=22, unique=True, db_index=True, default=generate_uuid)

    class Meta:
        abstract = True


class Attribute(models.Model):
    name = models.CharField(max_length=255, db_index=True)

    def __str__(self):
        return self.name


class AttributeValue(models.Model):
    attribute = models.ForeignKey(Attribute)
    value = models.CharField(max_length=255, blank=True, default='', db_index=True)
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = GenericForeignKey()

    def __str__(self):
        return '{}: {}'.format(self.attribute_id, self.value)


class Host(BaseUUID):
    parent = models.ForeignKey('self', related_name='children', blank=True, null=True)
    fqdn = models.CharField(verbose_name="FQDN", max_length=255)
    ip_address = models.GenericIPAddressField(protocol='both', verbose_name="IP Address", unique=True)
    username = models.CharField(max_length=255)
    is_primary = models.BooleanField(verbose_name="primary server", default=False, help_text="Is this the primary database server?")

    def __str__(self):
        return self.fqdn

    def save(self, *args, **kwargs):
        create_default_status = False
        if not self.pk:
            create_default_status = True
        super(Host, self).save(*args, **kwargs)
        if create_default_status:
            HostStatus.objects.create(host=self)

class HostStatus(models.Model):
    BRAND_NEW = 0
    CONNECTED = 1
    DISCONNECTED = 2
    DEPLOYED = 3
    PROMOTED = 4
    SHOT = 5

    STATUS_CHOICES = ((BRAND_NEW, 'Brand new'),
                      (CONNECTED, 'Connected'),
                      (DISCONNECTED, 'Disconnected'),
                      (DEPLOYED, 'Deployed'),
                      (PROMOTED, 'Promoted'),
                      (SHOT, 'Shot'))

    datetime = models.DateTimeField(auto_now=True)
    host = models.ForeignKey(Host, related_name='statuses')
    status = models.SmallIntegerField(choices=STATUS_CHOICES, blank=True, default=BRAND_NEW)

    class Meta:
        verbose_name = 'Host Status'
        verbose_name_plural = 'Host Statuses'

    def __str__(self):
        return '{} - {}'.format(self.host_id, self.get_status_display())

pg_ctrl/controller/forms.py
from django import forms
from django.core.urlresolvers import reverse_lazy
from monitor.views import check_connection
from .models import Host, Attribute, AttributeValue


def checkbox(placeholder, url):
    return forms.CheckboxInput(attrs=dict(placeholder=placeholder, url=url))


class ChecklistForm(forms.Form):
    hosts_created = forms.BooleanField(required=False,
                                       widget=checkbox(placeholder="Create hosts",
                                                       url=reverse_lazy("controller:create_host")),
                                       help_text="We need to add hosts that will be running the database server")
    keys_generated = forms.BooleanField(required=False,
                                        widget=checkbox(placeholder="How to generate key pair",
                                                        url="https://duckduckgo.com/?q=how+to+generate+public+and+private+keys&t=ha&ia=web"),
                                        help_text="You must generate a new public-private key pair and place "
                                                  "them in ~/.ssh folder as pg_ctrl.id_rsa and pg_ctrl.id_rsa.pub")
    public_key_installed = forms.BooleanField(required=False,
                                              widget=checkbox(placeholder="Check connection",
                                                              url=reverse_lazy("controller:create_host")),
                                              help_text="Public key must be placed on the hosts for this system "
                                                        "to be able to connect")
    checklist_completed = forms.BooleanField(required=False,
                                             widget=forms.HiddenInput())

    def save(self):
        for key, value in self.cleaned_data.items():
            if value:
                attr, _ = Attribute.objects.get_or_create(name=key)
                try:
                    AttributeValue.objects.get(attribute=attr)
                except AttributeValue.MultipleObjectsReturned:
                    AttributeValue.objects.filter(attribute=attr).delete()
                    AttributeValue.objects.create(attribute=attr, value=1)
                except AttributeValue.DoesNotExist:
                    AttributeValue.objects.create(attribute=attr, value=1)


class HostForm(forms.ModelForm):
    class Meta:
        model = Host
        fields = ('fqdn', 'ip_address', 'username', 'is_primary')

    def clean(self):
        cleaned_data = super(HostForm, self).clean()
        fqdn = cleaned_data.get('fqdn')
        ip_address = cleaned_data.get('ip_address')
        username = cleaned_data.get('username')
        connection_result = check_connection(ip_address, username)

        if connection_result['status'] != 'ok':
            raise forms.ValidationError(
                "Unable to connect to {} ({}) using {}".format(fqdn, ip_address, username))


class FailoverForm(forms.Form):
    host = forms.ModelChoiceField(queryset=Host.objects.filter(is_primary=False), required=True)


class StandbyForm(forms.Form):
    parent = forms.ModelChoiceField(queryset=Host.objects.all(), required=True)
    host = forms.ModelChoiceField(queryset=Host.objects.filter(is_primary=False), required=True)

pg_ctrl/controller/views.py
import os
import subprocess
import sys

from django import http
from django.conf import settings
from django.views import generic
from django.template import loader
from django.core.urlresolvers import reverse

import pydot

from .models import Host, AttributeValue
from .forms import HostForm, ChecklistForm, FailoverForm, StandbyForm


class ChecklistView(generic.FormView):
    template_name = 'controller/checklist_form.html'
    form_class = ChecklistForm

    def get(self, request, *args, **kwargs):
        checklist_completed = AttributeValue.objects.filter(attribute__name='checklist_completed',
                                                            value='1')
        if checklist_completed.exists():
            return http.HttpResponseRedirect(reverse('controller:inventory'))
        return super(ChecklistView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ChecklistView, self).get_context_data(**kwargs)
        context['hosts'] = Host.objects.all()
        return context

    def get_form_kwargs(self):
        kwargs = super(ChecklistView, self).get_form_kwargs()
        attr_values = AttributeValue.objects.filter(attribute__name__in=ChecklistForm.declared_fields.keys())
        kwargs['initial'] = dict([(av.attribute.name, av.value) for av in attr_values])
        return kwargs

    def form_valid(self, form):
        form.save()
        return http.HttpResponseRedirect(reverse('controller:checklist'))



class CreateHostView(generic.CreateView):
    template_name = 'controller/host_form.html'
    form_class = HostForm

    def get_success_url(self):
        return reverse('controller:create_host')

    def get_context_data(self, **kwargs):
        context = super(CreateHostView, self).get_context_data(**kwargs)
        context['hosts'] = Host.objects.all()
        return context


class DeleteHostView(generic.DeleteView):
    queryset = Host.objects.all()


def get_inventory_context():
    dot = pydot.Dot(graph_type='graph')

    def get_children(nodes):
        output = dict()
        for node in nodes:
            children = node.children.all()
            if children:
                output[node.pk] = get_children(children)
            else:
                output[node.pk] = {}
        return output

    def draw(parent_name, child_name):
        edge = pydot.Edge(parent_name, child_name)
        dot.add_edge(edge)

    def visit(node, parent=None):
        for k, v in node.iteritems():
            if isinstance(v, dict):
                # We start with the root node whose parent is None
                # we don't want to graph the None node
                if parent:
                    draw(parent, k)
                visit(v, k)
            else:
                draw(parent, k)
                # drawing the label using a distinct name
                draw(k, k + '_' + v)

    hosts = Host.objects.all()
    host_tree = get_children(hosts.filter(parent=None))

    dot = pydot.Dot(graph_type='digraph')
    visit(host_tree)
    host_tree = dot.to_string().replace('\n', '')

    return dict(hosts=hosts,
                host_tree=host_tree,
                private_key='{}/.ssh/pg_ctrl.id_rsa'.format(os.getenv('HOME')),
                python_executable=sys.executable)

class InventoryView(generic.TemplateView):
    template_name = 'controller/inventory.html'

    def get_context_data(self, **kwargs):
        context = super(InventoryView, self).get_context_data(**kwargs)
        context.update(get_inventory_context())
        return context



class BasePlaybookView(generic.TemplateView):
    template_name = 'controller/playbook.html'
    lock_path = os.path.join(settings.BASE_DIR, 'ansible.lock')
    inventory_path = os.path.join(settings.BASE_DIR, 'inventory')
    locked_message = 'There is a existing process. Wait for it to finish first.'

    def acquire_lock(self):
        open(self.lock_path, 'w').close()

    def release_lock(self):
        os.remove(self.lock_path)

    def is_locked(self):
        return os.path.exists(os.path.join(self.lock_path))

    def get_context_data(self, **kwargs):
        context = super(BasePlaybookView, self).get_context_data(**kwargs)
        context.update(get_inventory_context())
        return context

    def write_inventory(self):
        with open(self.inventory_path, 'w') as fsock:
            template = loader.get_template('controller/ansible_inventory.txt')
            rendered = template.render(self.get_context_data())
            fsock.write(rendered)

    def run_playbook(self, cmd, callback=None, *args):
        self.acquire_lock()
        process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
        for line in iter(process.stdout.readline, ''):
            yield line.rstrip() + '<br/>\n'

        if callback is not None:
            yield callback(*args)

        self.release_lock()


class PlaybookInstallView(BasePlaybookView):

    def post(self, request, *args, **kwargs):
        if self.is_locked():
            return http.HttpResponse(self.locked_message, status=400)

        self.acquire_lock()
        self.write_inventory()

        cmd = "ANSIBLE_HOST_KEY_CHECKING=False " \
              "ansible-playbook -i inventory playbook.yml " \
              "-e 'host_key_checking=False' --skip-tags failover"
        return http.StreamingHttpResponse(streaming_content=self.run_playbook(cmd))


class PlaybookFailoverView(BasePlaybookView):
    def get_context_data(self, **kwargs):
        context = super(PlaybookFailoverView, self).get_context_data(**kwargs)
        context['form'] = FailoverForm()
        return context

    def post_failover(self, primary_host, standby_host):
        primary_host.is_primary = False
        primary_host.save()

        standby_host.is_primary = True
        standby_host.save()

        self.write_inventory()

    def post(self, request, *args, **kwargs):
        form = FailoverForm(request.POST)
        if not form.is_valid():
            return http.HttpResponseBadRequest()

        standby_host = form.cleaned_data.get('host')

        if self.is_locked():
            return http.HttpResponse(self.locked_message, status=400)

        primary_host = Host.objects.filter(is_primary=True).first()
        cmd = "ANSIBLE_HOST_KEY_CHECKING=False " \
              "ansible-playbook -i inventory playbook.yml " \
              "--limit {},{} --tags failover".format(primary_host.fqdn,
                                                     standby_host.fqdn)
        return http.StreamingHttpResponse(streaming_content=self.run_playbook(cmd,
                                                                              self.post_failover,
                                                                              primary_host,
                                                                              standby_host))


class PlaybookAddStandbyView(BasePlaybookView):
    def get_context_data(self, **kwargs):
        context = super(PlaybookAddStandbyView, self).get_context_data(**kwargs)
        context['form'] = StandbyForm()
        return context

    def post(self, request, *args, **kwargs):
        form = StandbyForm(request.POST)
        if not form.is_valid():
            return http.HttpResponseBadRequest()

        parent_host = form.cleaned_data.get('parent')
        standby_host = form.cleaned_data.get('host')
        standby_host.parent = parent_host
        standby_host.save()

        if self.is_locked():
            return http.HttpResponse(self.locked_message, status=400)

        self.write_inventory()
        cmd = "ANSIBLE_HOST_KEY_CHECKING=False " \
              "ansible-playbook -i inventory playbook.yml " \
              "--limit {} --tags standby".format(standby_host.fqdn)
        return http.StreamingHttpResponse(streaming_content=self.run_playbook(cmd))

pg_ctrl/controller/templates/controller/checklist_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
{% endblock %}

{% block content %}
    <h3>Checklist</h3>

    <hr>

    <h5>Prerequisites</h5>

    <ul>
        <li>Server must have ssh up and running</li>
        <li>User must be able to sudo</li>
    </ul>

    <br>

    <form action="" method="post" class="form">
        {% csrf_token %}
        {% for field in form %}
            {% bootstrap_field field %}
            <a href="{{ field.field.widget.attrs.url }}"
               class="btn btn-link"
               rel="{{ field.name }}">{{ field.field.widget.attrs.placeholder }}</a>
            {% if field.name == "public_key_installed" %}
                <div id="connection_status"></div>
            {% endif %}
        {% endfor %}

        <button class="btn btn-primary hidden">Continue &raquo;</button>
    </form>

{% endblock %}


{% block javascript %}
    <script>
        var emitter = new EventEmitter();
        var hosts = [
            {% for host in hosts %}
                {'fqdn': '{{host.fqdn}}',
                 'ip_address': '{{ host.ip_address }}',
                 'username': '{{ host.username }}',
                 'state': 'fa fa-ellipsis-h'} {% if not forloop.last %}, {% endif %}
            {% endfor %}
        ];
        var connection_check_url = '{% url "monitor:check_connection" %}';
    </script>

    <script type="text/babel">
        var ConnectionStatus = React.createClass({
            getInitialState: function () {
                return {
                    hosts: hosts
                }
            },

            componentDidMount: function () {
                var hosts = this.state.hosts;
                var self = this;
                var completed = 0;
                this.state.hosts.forEach(function (host, index) {
                    host.state = 'fa fa-spinner fa-spin';
                    hosts[index] = host;
                    self.setState({hosts: hosts});

                    $.ajax({
                        url: connection_check_url,
                        method: 'GET',
                        data: {host: host.ip_address, username: host.username}
                    }).done((data) => {
                        host.state = 'fa fa-check';
                        hosts[index] = host;
                        self.setState({hosts: hosts});
                        completed += 1;
                        if (completed === hosts.length) {
                            $('#id_public_key_installed').prop('checked', 'checked');
                            $('#id_checklist_completed').val('1');
                            $('form button').removeClass('hidden');
                        }
                    }).fail((xhr) => {
                        host.state = 'fa fa-times';
                        hosts[index] = host;
                        self.setState({hosts: hosts});

                        alert("One or more connections have failed. Make sure the hosts are up and running.");
                    });
                });
            },

            render: function () {
                var hosts = this.state.hosts.map(function (host) {
                    return <li key={host.fqdn}>{host.fqdn} <i className={host.state}></i></li>
                });
                return <ul>{hosts}</ul>
            }
        });

        $('a[rel=public_key_installed').on('click', function (e) {
            e.preventDefault();

            ReactDOM.render(
                <ConnectionStatus />,
                document.getElementById('connection_status')
            );
        });


    </script>
{% endblock %}

pg_ctrl/controller/templates/controller/host.html
<li>{{ host.fqdn }}</li>

pg_ctrl/controller/templates/controller/host_form.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
    <h1>Hosts</h1>
    <hr>

    <div class="row">

        <div class="col-sm-6">
            <ul class="list">
                {% for host in hosts %}
                    <li>{{ host.fqdn }}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="col-sm-6">
            <h3>Add new</h3>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        Add
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>

    {% if hosts|length > 0 %}
    <div class="row">
        <div class="col-sm-12 text-center">
            <form action="{% url "controller:checklist" %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="hosts_created" value="on">
                <button type="submit" class="btn btn-primary">Done</button>
            </form>
        </div>
    </div>
    {% endif %}
{% endblock %}

pg_ctrl/controller/templates/controller/inventory.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.min.css">
    <style type="text/css">
        #mynetwork {
            width: 600px;
            height: 400px;
            border: 1px solid lightgray;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h2>Hosts</h2>
            <hr>

            <div id="mynetwork"></div>

            {{ host_tree }}

            <ul class="list">
                {% for host in hosts %}
                    {% include 'controller/host.html' with host=host %}
                    {% if host.children.count %}
                        <ul>
                            {% for child_obj in host.children.all %}
                                {% include 'controller/host.html' with host=child_obj %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-6">
            <pre class="console">{% include "controller/ansible_inventory.txt" %}</pre>
        </div>
    </div>

    <form action="{% url "controller:playbook_install" %}" method="post">
        {% csrf_token %}
        <button class="btn btn-primary">Save</button>
    </form>
{% endblock %}

{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.min.js"></script>
    <script>
        // create an array with nodes
        var nodes = new vis.DataSet([
            {% for host in hosts %}
                {id: {{ host.pk }}, label: '{{ host.fqdn }}{% if host.is_primary %}\nPrimary{% endif %}'}{% if not forloop.last %},{% endif %}
            {% endfor %}
        ]);

        var DOTstring = '{{ host_tree|safe }}';
        var parsedData = vis.network.convertDot(DOTstring);


        // create a network
        var container = document.getElementById('mynetwork');

        // provide the data in the vis format
        var data = {
            nodes: nodes,
            edges: parsedData.edges
        };
        var options = {
            nodes: {
                shape: "box"
            },
            layout: {
                hierarchical: {
                    direction: "UD",
                    nodeSpacing: 200,
                    parentCentralization: true,
                    sortMethod: "directed"
                }
            }
        };

        // initialize your network!
        var network = new vis.Network(container, data, options);
    </script>
{% endblock %}

pg_ctrl/controller/templates/controller/playbook.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button>Submit</button>
    </form>
{% endblock %}