pg_ctrl/controller/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^checklist/$', views.ChecklistView.as_view(), name='checklist'),
    url(r'^inventory/$', views.InventoryView.as_view(), name='inventory'),
    url(r'^playbook/install/$', views.PlaybookInstallView.as_view(), name='playbook_install'),
    url(r'^playbook/failover/$', views.PlaybookFailoverView.as_view(), name='playbook_failover'),
    url(r'^playbook/add_standby/$', views.PlaybookAddStandbyView.as_view(), name='playbook_add_standby'),

    url(r'^hosts/create/$', views.CreateHostView.as_view(), name='create_host'),
]

pg_ctrl/monitor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^check_connection/$', views.CheckConnectionView.as_view(), name='check_connection'),
]

pg_ctrl/pg_ctrl/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^controller/', include("controller.urls", namespace="controller")),
    url(r'^monitor/', include("monitor.urls", namespace="monitor")),
]

pg_ctrl/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>PG CTRL</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static "css/master.css" %}" rel="stylesheet">

    {% block css %}{% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react-dom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/EventEmitter/5.1.0/EventEmitter.min.js"></script>

</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">PG CTRL</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url "controller:inventory" %}">Inventory <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 main">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% block javascript %}{% endblock %}
</body>
</html>